apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: domain-tls
spec:
  secretName: domain-tls
  dnsNames:
    - "bluehook-worker-dedi.astrid.place"
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
