service: worker
image: ghcr.io/iamjsd/bluehook/worker

servers:
  web:
    - <%= ENV['SERVER_IP'] %>

proxy: 
  ssl: true
  host: <%= ENV['SERVER_HOSTNAME'] %>
  app_port: 6969

registry:
  server: ghcr.io
  username: <%= ENV['GITHUB_ACTOR'] %>
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  secret:
    - PG_CONNECTION_STRING
    - HTTP_KEY
